version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: transactions_postgres
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: transactions_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 